"""Verification plan for doccloud_comment."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "ceiling_create_document_authenticated",
            "description": "CreateDocument is only allowed for authenticated users",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"CreateDocument\"",
            "resource_type": "Drive",
            "reference_path": os.path.join(REFS, "ceiling_create_document_authenticated.cedar"),
        },
        {
            "name": "ceiling_create_group_authenticated",
            "description": "CreateGroup is only allowed for authenticated users",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"CreateGroup\"",
            "resource_type": "Drive",
            "reference_path": os.path.join(REFS, "ceiling_create_group_authenticated.cedar"),
        },
        {
            "name": "ceiling_modify_group_owner_authenticated",
            "description": "ModifyGroup is only allowed for the authenticated group owner",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyGroup\"",
            "resource_type": "Group",
            "reference_path": os.path.join(REFS, "ceiling_modify_group_owner_authenticated.cedar"),
        },
        {
            "name": "ceiling_delete_group_owner_authenticated",
            "description": "DeleteGroup is only allowed for the authenticated group owner",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
            "reference_path": os.path.join(REFS, "ceiling_delete_group_owner_authenticated.cedar"),
        },
        {
            "name": "ceiling_view_document_user",
            "description": "A user may view a document only if authenticated, unblocked, and owner or in viewACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view_document_user.cedar"),
        },
        {
            "name": "ceiling_view_document_public",
            "description": "Public may view a document only when publicAccess is view or edit",
            "type": "implies",
            "principal_type": "Public",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_view_document_public.cedar"),
        },
        {
            "name": "ceiling_modify_document",
            "description": "A user may modify a document only if authenticated, unblocked, and owner or in modifyACL",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_modify_document.cedar"),
        },
        {
            "name": "ceiling_delete_document",
            "description": "DeleteDocument is only allowed for authenticated owners or manageACL members",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_delete_document.cedar"),
        },
        {
            "name": "ceiling_edit_is_private",
            "description": "EditIsPrivate is only allowed for authenticated owners or manageACL members",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"EditIsPrivate\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit_is_private.cedar"),
        },
        {
            "name": "ceiling_edit_public_access",
            "description": "EditPublicAccess is only allowed for authenticated owners or manageACL members",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"EditPublicAccess\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_edit_public_access.cedar"),
        },
        {
            "name": "ceiling_add_to_share_acl",
            "description": "AddToShareACL is only allowed for authenticated owners or manageACL members",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
            "reference_path": os.path.join(REFS, "ceiling_add_to_share_acl.cedar"),
        },
        {
            "name": "ceiling_add_comment",
            "description": "AddComment is only allowed when the user can view the parent document and blocking does not apply",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"AddComment\"",
            "resource_type": "Comment",
            "reference_path": os.path.join(REFS, "ceiling_add_comment.cedar"),
        },
        {
            "name": "ceiling_edit_comment",
            "description": "EditComment is only allowed for the comment author",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"EditComment\"",
            "resource_type": "Comment",
            "reference_path": os.path.join(REFS, "ceiling_edit_comment.cedar"),
        },
        {
            "name": "ceiling_delete_comment",
            "description": "DeleteComment is only allowed for the author, document owner, or document manageACL member",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteComment\"",
            "resource_type": "Comment",
            "reference_path": os.path.join(REFS, "ceiling_delete_comment.cedar"),
        },
        {
            "name": "floor_create_document_authenticated",
            "description": "An authenticated user must be able to create a document",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"CreateDocument\"",
            "resource_type": "Drive",
            "floor_path": os.path.join(REFS, "floor_create_document_authenticated.cedar"),
        },
        {
            "name": "floor_create_group_authenticated",
            "description": "An authenticated user must be able to create a group",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"CreateGroup\"",
            "resource_type": "Drive",
            "floor_path": os.path.join(REFS, "floor_create_group_authenticated.cedar"),
        },
        {
            "name": "floor_owner_view_document",
            "description": "An authenticated unblocked document owner must be able to view the document",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_view_document.cedar"),
        },
        {
            "name": "floor_view_acl_view_document",
            "description": "An authenticated unblocked viewACL member must be able to view the document",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_view_acl_view_document.cedar"),
        },
        {
            "name": "floor_public_view_document",
            "description": "Public must be able to view when publicAccess is view",
            "type": "floor",
            "principal_type": "Public",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_public_view_document.cedar"),
        },
        {
            "name": "floor_owner_modify_document",
            "description": "An authenticated unblocked document owner must be able to modify the document",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_modify_document.cedar"),
        },
        {
            "name": "floor_modify_acl_modify_document",
            "description": "An authenticated unblocked modifyACL member must be able to modify the document",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_modify_acl_modify_document.cedar"),
        },
        {
            "name": "floor_owner_delete_document",
            "description": "An authenticated document owner must be able to delete the document",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_delete_document.cedar"),
        },
        {
            "name": "floor_manage_acl_delete_document",
            "description": "An authenticated manageACL member must be able to delete the document",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_manage_acl_delete_document.cedar"),
        },
        {
            "name": "floor_owner_edit_is_private",
            "description": "An authenticated document owner must be able to edit privacy",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"EditIsPrivate\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_edit_is_private.cedar"),
        },
        {
            "name": "floor_manage_acl_edit_is_private",
            "description": "An authenticated manageACL member must be able to edit privacy",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"EditIsPrivate\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_manage_acl_edit_is_private.cedar"),
        },
        {
            "name": "floor_owner_edit_public_access",
            "description": "An authenticated document owner must be able to edit publicAccess",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"EditPublicAccess\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_edit_public_access.cedar"),
        },
        {
            "name": "floor_manage_acl_edit_public_access",
            "description": "An authenticated manageACL member must be able to edit publicAccess",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"EditPublicAccess\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_manage_acl_edit_public_access.cedar"),
        },
        {
            "name": "floor_owner_add_to_share_acl",
            "description": "An authenticated document owner must be able to add to share ACL",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_owner_add_to_share_acl.cedar"),
        },
        {
            "name": "floor_manage_acl_add_to_share_acl",
            "description": "An authenticated manageACL member must be able to add to share ACL",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
            "floor_path": os.path.join(REFS, "floor_manage_acl_add_to_share_acl.cedar"),
        },
        {
            "name": "floor_owner_modify_group",
            "description": "An authenticated group owner must be able to modify the group",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ModifyGroup\"",
            "resource_type": "Group",
            "floor_path": os.path.join(REFS, "floor_owner_modify_group.cedar"),
        },
        {
            "name": "floor_owner_delete_group",
            "description": "An authenticated group owner must be able to delete the group",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
            "floor_path": os.path.join(REFS, "floor_owner_delete_group.cedar"),
        },
        {
            "name": "floor_owner_add_comment",
            "description": "A document owner must be able to add a comment on their document when unblocked",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"AddComment\"",
            "resource_type": "Comment",
            "floor_path": os.path.join(REFS, "floor_owner_add_comment.cedar"),
        },
        {
            "name": "floor_view_acl_add_comment",
            "description": "A viewACL member must be able to add a comment when unblocked",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"AddComment\"",
            "resource_type": "Comment",
            "floor_path": os.path.join(REFS, "floor_view_acl_add_comment.cedar"),
        },
        {
            "name": "floor_author_edit_comment",
            "description": "The author must be able to edit their comment",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"EditComment\"",
            "resource_type": "Comment",
            "floor_path": os.path.join(REFS, "floor_author_edit_comment.cedar"),
        },
        {
            "name": "floor_author_delete_comment",
            "description": "The author must be able to delete their comment",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteComment\"",
            "resource_type": "Comment",
            "floor_path": os.path.join(REFS, "floor_author_delete_comment.cedar"),
        },
        {
            "name": "floor_document_owner_delete_comment",
            "description": "The document owner must be able to delete comments on their document",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteComment\"",
            "resource_type": "Comment",
            "floor_path": os.path.join(REFS, "floor_document_owner_delete_comment.cedar"),
        },
        {
            "name": "floor_manage_acl_delete_comment",
            "description": "A document manageACL member must be able to delete comments on the document",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteComment\"",
            "resource_type": "Comment",
            "floor_path": os.path.join(REFS, "floor_manage_acl_delete_comment.cedar"),
        },
        {
            "name": "liveness_create_document",
            "description": "CreateDocument is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"CreateDocument\"",
            "resource_type": "Drive",
        },
        {
            "name": "liveness_create_group",
            "description": "CreateGroup is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"CreateGroup\"",
            "resource_type": "Drive",
        },
        {
            "name": "liveness_view_document",
            "description": "ViewDocument is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ViewDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_modify_document",
            "description": "ModifyDocument is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ModifyDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_delete_document",
            "description": "DeleteDocument is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"DeleteDocument\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_edit_is_private",
            "description": "EditIsPrivate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"EditIsPrivate\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_edit_public_access",
            "description": "EditPublicAccess is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"EditPublicAccess\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_add_to_share_acl",
            "description": "AddToShareACL is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"AddToShareACL\"",
            "resource_type": "Document",
        },
        {
            "name": "liveness_modify_group",
            "description": "ModifyGroup is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ModifyGroup\"",
            "resource_type": "Group",
        },
        {
            "name": "liveness_delete_group",
            "description": "DeleteGroup is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"DeleteGroup\"",
            "resource_type": "Group",
        },
        {
            "name": "liveness_add_comment",
            "description": "AddComment is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"AddComment\"",
            "resource_type": "Comment",
        },
        {
            "name": "liveness_edit_comment",
            "description": "EditComment is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"EditComment\"",
            "resource_type": "Comment",
        },
        {
            "name": "liveness_delete_comment",
            "description": "DeleteComment is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"DeleteComment\"",
            "resource_type": "Comment",
        },
    ]
