"""Verification plan for sales_remove_template."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "ceiling_viewPresentation",
            "description": "viewPresentation is only permitted for internal users or users in the presentation viewers/editors sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_viewPresentation.cedar"),
        },
        {
            "name": "ceiling_removeSelfAccessFromPresentation",
            "description": "removeSelfAccessFromPresentation is only permitted for users in the presentation viewers/editors sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_removeSelfAccessFromPresentation.cedar"),
        },
        {
            "name": "ceiling_duplicatePresentation",
            "description": "duplicatePresentation is only permitted for internal users or presentation editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_duplicatePresentation.cedar"),
        },
        {
            "name": "ceiling_editPresentation",
            "description": "editPresentation is only permitted for internal users or non-customer presentation editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_editPresentation.cedar"),
        },
        {
            "name": "ceiling_grantViewAccessToPresentation",
            "description": "grantViewAccessToPresentation is only permitted for presentation editors and only for targets already in viewers or editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_grantViewAccessToPresentation.cedar"),
        },
        {
            "name": "ceiling_grantEditAccessToPresentation",
            "description": "grantEditAccessToPresentation is only permitted for presentation editors and only for targets already in editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_grantEditAccessToPresentation.cedar"),
        },
        {
            "name": "floor_internal_viewPresentation",
            "description": "Internal users must be able to viewPresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_internal_viewPresentation.cedar"),
        },
        {
            "name": "floor_external_viewer_removeSelfAccessFromPresentation",
            "description": "External listed viewers must be able to removeSelfAccessFromPresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_external_viewer_removeSelfAccessFromPresentation.cedar"),
        },
        {
            "name": "floor_external_editor_duplicatePresentation",
            "description": "External listed editors must be able to duplicatePresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_external_editor_duplicatePresentation.cedar"),
        },
        {
            "name": "floor_internal_editPresentation",
            "description": "Internal users must be able to editPresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_internal_editPresentation.cedar"),
        },
        {
            "name": "floor_external_editor_editPresentation",
            "description": "Non-customer external editors must be able to editPresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_external_editor_editPresentation.cedar"),
        },
        {
            "name": "floor_external_editor_grantViewAccessToPresentation",
            "description": "External listed editors must be able to grantViewAccessToPresentation for a listed target",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_external_editor_grantViewAccessToPresentation.cedar"),
        },
        {
            "name": "floor_external_editor_grantEditAccessToPresentation",
            "description": "External listed editors must be able to grantEditAccessToPresentation for a listed editor target",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_external_editor_grantEditAccessToPresentation.cedar"),
        },
        {
            "name": "liveness_viewPresentation",
            "description": "viewPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_removeSelfAccessFromPresentation",
            "description": "removeSelfAccessFromPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_duplicatePresentation",
            "description": "duplicatePresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_editPresentation",
            "description": "editPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_grantViewAccessToPresentation",
            "description": "grantViewAccessToPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_grantEditAccessToPresentation",
            "description": "grantEditAccessToPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
        },
    ]
