"""Verification plan for streaming_family_plan."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "ceiling_freemember_watch_movie",
            "description": "FreeMember may watch a Movie only when it is free or delegated by subscriberPlan, and not during kid bedtime",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "ceiling_freemember_watch_movie.cedar"),
        },
        {
            "name": "ceiling_freemember_watch_show",
            "description": "FreeMember may watch a Show only when it is free or delegated by subscriberPlan under subscriber early-access rules, and not during kid bedtime",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "reference_path": os.path.join(REFS, "ceiling_freemember_watch_show.cedar"),
        },
        {
            "name": "ceiling_subscriber_watch_movie",
            "description": "Subscriber may watch a Movie only when !needsRentOrBuy and not during kid bedtime",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "ceiling_subscriber_watch_movie.cedar"),
        },
        {
            "name": "ceiling_subscriber_watch_show",
            "description": "Subscriber may watch a Show only when early-access timing allows it and not during kid bedtime",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "reference_path": os.path.join(REFS, "ceiling_subscriber_watch_show.cedar"),
        },
        {
            "name": "ceiling_freemember_no_rent",
            "description": "FreeMember cannot rent a Movie",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"rent\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "ceiling_freemember_no_rent.cedar"),
        },
        {
            "name": "ceiling_freemember_no_buy",
            "description": "FreeMember cannot buy a Movie",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"buy\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "ceiling_freemember_no_buy.cedar"),
        },
        {
            "name": "ceiling_subscriber_rent",
            "description": "Subscriber may rent only Oscar-nominated Movies in the promo window",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"rent\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "ceiling_subscriber_rent.cedar"),
        },
        {
            "name": "ceiling_subscriber_buy",
            "description": "Subscriber may buy only Oscar-nominated Movies in the promo window",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"buy\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "ceiling_subscriber_buy.cedar"),
        },
        {
            "name": "floor_freemember_watch_free_movie_no_kid",
            "description": "A non-kid FreeMember must be able to watch a free Movie",
            "type": "floor",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "floor_freemember_watch_free_movie_no_kid.cedar"),
        },
        {
            "name": "floor_freemember_watch_free_show_no_kid",
            "description": "A non-kid FreeMember must be able to watch a free Show",
            "type": "floor",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "floor_path": os.path.join(REFS, "floor_freemember_watch_free_show_no_kid.cedar"),
        },
        {
            "name": "floor_family_watch_movie_no_kid",
            "description": "A non-kid family member must be able to watch any Movie through subscriberPlan delegation",
            "type": "floor",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "floor_family_watch_movie_no_kid.cedar"),
        },
        {
            "name": "floor_family_watch_show_not_early_no_kid",
            "description": "A non-kid family member must be able to watch a non-early Show through subscriberPlan delegation",
            "type": "floor",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "floor_path": os.path.join(REFS, "floor_family_watch_show_not_early_no_kid.cedar"),
        },
        {
            "name": "floor_family_watch_show_premium_early_no_kid",
            "description": "A non-kid family member of a premium subscriber must be able to watch an early-access Show within 24 hours of release",
            "type": "floor",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "floor_path": os.path.join(REFS, "floor_family_watch_show_premium_early_no_kid.cedar"),
        },
        {
            "name": "floor_subscriber_watch_movie_no_rent_no_kid",
            "description": "A non-kid Subscriber must be able to watch a Movie that does not need rent or buy",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "floor_subscriber_watch_movie_no_rent_no_kid.cedar"),
        },
        {
            "name": "floor_subscriber_watch_show_not_early_no_kid",
            "description": "A non-kid Subscriber must be able to watch a non-early Show",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "floor_path": os.path.join(REFS, "floor_subscriber_watch_show_not_early_no_kid.cedar"),
        },
        {
            "name": "floor_subscriber_watch_show_premium_early_no_kid",
            "description": "A non-kid premium Subscriber must be able to watch an early-access Show within 24 hours of release",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "floor_path": os.path.join(REFS, "floor_subscriber_watch_show_premium_early_no_kid.cedar"),
        },
        {
            "name": "floor_subscriber_rent_oscar_in_window",
            "description": "A Subscriber must be able to rent an Oscar-nominated Movie in the promo window",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"rent\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "floor_subscriber_rent_oscar_in_window.cedar"),
        },
        {
            "name": "floor_subscriber_buy_oscar_in_window",
            "description": "A Subscriber must be able to buy an Oscar-nominated Movie in the promo window",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"buy\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "floor_subscriber_buy_oscar_in_window.cedar"),
        },
        {
            "name": "liveness_freemember_watch_movie",
            "description": "FreeMember watch Movie is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
        },
        {
            "name": "liveness_freemember_watch_show",
            "description": "FreeMember watch Show is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
        },
        {
            "name": "liveness_subscriber_watch_movie",
            "description": "Subscriber watch Movie is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
        },
        {
            "name": "liveness_subscriber_watch_show",
            "description": "Subscriber watch Show is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
        },
        {
            "name": "liveness_subscriber_rent",
            "description": "Subscriber rent Movie is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"rent\"",
            "resource_type": "Movie",
        },
        {
            "name": "liveness_subscriber_buy",
            "description": "Subscriber buy Movie is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"buy\"",
            "resource_type": "Movie",
        },
    ]
