"""Verification plan for sales_self_grant_forbid."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "ceiling_viewPresentation",
            "description": "viewPresentation is only permitted for internal users or users in the presentation viewers/editors sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_viewPresentation.cedar"),
        },
        {
            "name": "ceiling_removeSelfAccessFromPresentation",
            "description": "removeSelfAccessFromPresentation is only permitted for users in the presentation viewers/editors sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_removeSelfAccessFromPresentation.cedar"),
        },
        {
            "name": "ceiling_duplicatePresentation",
            "description": "duplicatePresentation is only permitted for internal users or presentation editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_duplicatePresentation.cedar"),
        },
        {
            "name": "ceiling_editPresentation",
            "description": "editPresentation is only permitted for internal users or non-customer editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_editPresentation.cedar"),
        },
        {
            "name": "ceiling_grantViewAccessToPresentation",
            "description": "grantViewAccessToPresentation is only permitted for presentation editors, for listed targets, and never for self-grants",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_grantViewAccessToPresentation.cedar"),
        },
        {
            "name": "ceiling_grantEditAccessToPresentation",
            "description": "grantEditAccessToPresentation is only permitted for presentation editors, for listed editor targets, and never for self-grants",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_grantEditAccessToPresentation.cedar"),
        },
        {
            "name": "ceiling_viewTemplate",
            "description": "viewTemplate is only permitted for internal users, listed viewers, viewer-market members, or listed editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_viewTemplate.cedar"),
        },
        {
            "name": "ceiling_duplicateTemplate",
            "description": "duplicateTemplate is only permitted for internal users, listed viewers, viewer-market members, or listed editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"duplicateTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_duplicateTemplate.cedar"),
        },
        {
            "name": "ceiling_removeSelfAccessFromTemplate",
            "description": "removeSelfAccessFromTemplate is only permitted for internal users or users directly listed in viewers/editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_removeSelfAccessFromTemplate.cedar"),
        },
        {
            "name": "ceiling_editTemplate",
            "description": "editTemplate is only permitted for internal users or non-customer listed editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_editTemplate.cedar"),
        },
        {
            "name": "ceiling_removeOthersAccessToTemplate",
            "description": "removeOthersAccessToTemplate is only permitted for internal users or listed editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeOthersAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_removeOthersAccessToTemplate.cedar"),
        },
        {
            "name": "ceiling_grantViewAccessToTemplate",
            "description": "grantViewAccessToTemplate is only permitted for internal users when exactly one target is provided, and user-target self-grants are forbidden",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_grantViewAccessToTemplate.cedar"),
        },
        {
            "name": "ceiling_grantEditAccessToTemplate",
            "description": "grantEditAccessToTemplate is only permitted for internal users when exactly one target is provided, and user-target self-grants are forbidden",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_grantEditAccessToTemplate.cedar"),
        },
        {
            "name": "floor_internal_viewPresentation",
            "description": "Internal users must be able to viewPresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_internal_viewPresentation.cedar"),
        },
        {
            "name": "floor_external_viewer_removeSelfAccessFromPresentation",
            "description": "External listed viewers must be able to removeSelfAccessFromPresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_external_viewer_removeSelfAccessFromPresentation.cedar"),
        },
        {
            "name": "floor_external_editor_duplicatePresentation",
            "description": "External listed editors must be able to duplicatePresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_external_editor_duplicatePresentation.cedar"),
        },
        {
            "name": "floor_external_editor_editPresentation",
            "description": "Non-customer external editors must be able to editPresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_external_editor_editPresentation.cedar"),
        },
        {
            "name": "floor_external_editor_grantViewAccessToPresentation",
            "description": "External listed editors must be able to grantViewAccessToPresentation for another listed target",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_external_editor_grantViewAccessToPresentation.cedar"),
        },
        {
            "name": "floor_external_editor_grantEditAccessToPresentation",
            "description": "External listed editors must be able to grantEditAccessToPresentation for another listed editor target",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_external_editor_grantEditAccessToPresentation.cedar"),
        },
        {
            "name": "floor_internal_viewTemplate",
            "description": "Internal users must be able to viewTemplate",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_internal_viewTemplate.cedar"),
        },
        {
            "name": "floor_external_market_duplicateTemplate",
            "description": "External users in a viewer market must be able to duplicateTemplate",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"duplicateTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_external_market_duplicateTemplate.cedar"),
        },
        {
            "name": "floor_internal_removeSelfAccessFromTemplate",
            "description": "Internal users must be able to removeSelfAccessFromTemplate",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_internal_removeSelfAccessFromTemplate.cedar"),
        },
        {
            "name": "floor_internal_editTemplate",
            "description": "Internal users must be able to editTemplate",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_internal_editTemplate.cedar"),
        },
        {
            "name": "floor_external_editor_removeOthersAccessToTemplate",
            "description": "External listed editors must be able to removeOthersAccessToTemplate",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"removeOthersAccessToTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_external_editor_removeOthersAccessToTemplate.cedar"),
        },
        {
            "name": "floor_internal_grantViewAccessToTemplate",
            "description": "Internal users must be able to grantViewAccessToTemplate to another user when exactly one target is provided",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_internal_grantViewAccessToTemplate.cedar"),
        },
        {
            "name": "floor_internal_grantEditAccessToTemplate",
            "description": "Internal users must be able to grantEditAccessToTemplate to another user when exactly one target is provided",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_internal_grantEditAccessToTemplate.cedar"),
        },
        {
            "name": "liveness_viewPresentation",
            "description": "viewPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_removeSelfAccessFromPresentation",
            "description": "removeSelfAccessFromPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_duplicatePresentation",
            "description": "duplicatePresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_editPresentation",
            "description": "editPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_grantViewAccessToPresentation",
            "description": "grantViewAccessToPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_grantEditAccessToPresentation",
            "description": "grantEditAccessToPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_viewTemplate",
            "description": "viewTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_duplicateTemplate",
            "description": "duplicateTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"duplicateTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_removeSelfAccessFromTemplate",
            "description": "removeSelfAccessFromTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_editTemplate",
            "description": "editTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_removeOthersAccessToTemplate",
            "description": "removeOthersAccessToTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"removeOthersAccessToTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_grantViewAccessToTemplate",
            "description": "grantViewAccessToTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_grantEditAccessToTemplate",
            "description": "grantEditAccessToTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToTemplate\"",
            "resource_type": "Template",
        },
    ]
