"""Verification plan for hotel_partner_access."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "ceiling_viewReservation",
            "description": "viewReservation is only permitted if the user has view, member, or admin scope over the reservation's property or hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_viewReservation.cedar"),
        },
        {
            "name": "ceiling_updateReservation",
            "description": "updateReservation is only permitted if the user has member or admin scope over the reservation's property or hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_updateReservation.cedar"),
        },
        {
            "name": "ceiling_grantAccessReservation",
            "description": "grantAccessReservation is only permitted if the user has admin scope over the reservation's property or hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessReservation.cedar"),
        },
        {
            "name": "ceiling_createReservation",
            "description": "createReservation is only permitted if the user has member or admin scope over the property or its hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_createReservation.cedar"),
        },
        {
            "name": "ceiling_viewProperty",
            "description": "viewProperty is only permitted if the user has view, member, or admin scope over the property or its hotel, or presents the property's non-empty partner code",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_viewProperty.cedar"),
        },
        {
            "name": "ceiling_updateProperty",
            "description": "updateProperty is only permitted if the user has member or admin scope over the property or its hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_updateProperty.cedar"),
        },
        {
            "name": "ceiling_grantAccessProperty",
            "description": "grantAccessProperty is only permitted if the user has admin scope over the property or its hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessProperty\"",
            "resource_type": "Property",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessProperty.cedar"),
        },
        {
            "name": "ceiling_createProperty",
            "description": "createProperty is only permitted if the user has member or admin scope over the hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createProperty\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_createProperty.cedar"),
        },
        {
            "name": "ceiling_createHotel",
            "description": "createHotel is only permitted if the user has admin scope over the hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"createHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_createHotel.cedar"),
        },
        {
            "name": "ceiling_viewHotel",
            "description": "viewHotel is only permitted if the user has view, member, or admin scope over the hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_viewHotel.cedar"),
        },
        {
            "name": "ceiling_updateHotel",
            "description": "updateHotel is only permitted if the user has member or admin scope over the hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"updateHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_updateHotel.cedar"),
        },
        {
            "name": "ceiling_grantAccessHotel",
            "description": "grantAccessHotel is only permitted if the user has admin scope over the hotel",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantAccessHotel\"",
            "resource_type": "Hotel",
            "reference_path": os.path.join(REFS, "ceiling_grantAccessHotel.cedar"),
        },
        {
            "name": "floor_viewReservation_viewer",
            "description": "A property reservation viewer must be able to viewReservation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_viewReservation_viewer.cedar"),
        },
        {
            "name": "floor_updateReservation_member",
            "description": "A property reservation member must be able to updateReservation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_updateReservation_member.cedar"),
        },
        {
            "name": "floor_grantAccessReservation_admin",
            "description": "A property admin must be able to grantAccessReservation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
            "floor_path": os.path.join(REFS, "floor_grantAccessReservation_admin.cedar"),
        },
        {
            "name": "floor_createReservation_member",
            "description": "A property reservation member must be able to createReservation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
            "floor_path": os.path.join(REFS, "floor_createReservation_member.cedar"),
        },
        {
            "name": "floor_viewProperty_viewer",
            "description": "A property reservation viewer must be able to viewProperty",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewProperty\"",
            "resource_type": "Property",
            "floor_path": os.path.join(REFS, "floor_viewProperty_viewer.cedar"),
        },
        {
            "name": "floor_viewProperty_partner",
            "description": "Any user with the matching non-empty partner code must be able to viewProperty",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewProperty\"",
            "resource_type": "Property",
            "floor_path": os.path.join(REFS, "floor_viewProperty_partner.cedar"),
        },
        {
            "name": "floor_updateProperty_member",
            "description": "A property reservation member must be able to updateProperty",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"updateProperty\"",
            "resource_type": "Property",
            "floor_path": os.path.join(REFS, "floor_updateProperty_member.cedar"),
        },
        {
            "name": "floor_grantAccessProperty_admin",
            "description": "A property admin must be able to grantAccessProperty",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantAccessProperty\"",
            "resource_type": "Property",
            "floor_path": os.path.join(REFS, "floor_grantAccessProperty_admin.cedar"),
        },
        {
            "name": "floor_createProperty_member",
            "description": "A hotel reservation member must be able to createProperty",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"createProperty\"",
            "resource_type": "Hotel",
            "floor_path": os.path.join(REFS, "floor_createProperty_member.cedar"),
        },
        {
            "name": "floor_createHotel_admin",
            "description": "A hotel admin must be able to createHotel",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"createHotel\"",
            "resource_type": "Hotel",
            "floor_path": os.path.join(REFS, "floor_createHotel_admin.cedar"),
        },
        {
            "name": "floor_viewHotel_viewer",
            "description": "A hotel reservation viewer must be able to viewHotel",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewHotel\"",
            "resource_type": "Hotel",
            "floor_path": os.path.join(REFS, "floor_viewHotel_viewer.cedar"),
        },
        {
            "name": "floor_updateHotel_member",
            "description": "A hotel reservation member must be able to updateHotel",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"updateHotel\"",
            "resource_type": "Hotel",
            "floor_path": os.path.join(REFS, "floor_updateHotel_member.cedar"),
        },
        {
            "name": "floor_grantAccessHotel_admin",
            "description": "A hotel admin must be able to grantAccessHotel",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantAccessHotel\"",
            "resource_type": "Hotel",
            "floor_path": os.path.join(REFS, "floor_grantAccessHotel_admin.cedar"),
        },
        {
            "name": "liveness_viewReservation",
            "description": "viewReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_updateReservation",
            "description": "updateReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"updateReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_grantAccessReservation",
            "description": "grantAccessReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantAccessReservation\"",
            "resource_type": "Reservation",
        },
        {
            "name": "liveness_createReservation",
            "description": "createReservation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"createReservation\"",
            "resource_type": "Property",
        },
        {
            "name": "liveness_viewProperty",
            "description": "viewProperty is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewProperty\"",
            "resource_type": "Property",
        },
        {
            "name": "liveness_updateProperty",
            "description": "updateProperty is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"updateProperty\"",
            "resource_type": "Property",
        },
        {
            "name": "liveness_grantAccessProperty",
            "description": "grantAccessProperty is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantAccessProperty\"",
            "resource_type": "Property",
        },
        {
            "name": "liveness_createProperty",
            "description": "createProperty is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"createProperty\"",
            "resource_type": "Hotel",
        },
        {
            "name": "liveness_createHotel",
            "description": "createHotel is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"createHotel\"",
            "resource_type": "Hotel",
        },
        {
            "name": "liveness_viewHotel",
            "description": "viewHotel is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewHotel\"",
            "resource_type": "Hotel",
        },
        {
            "name": "liveness_updateHotel",
            "description": "updateHotel is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"updateHotel\"",
            "resource_type": "Hotel",
        },
        {
            "name": "liveness_grantAccessHotel",
            "description": "grantAccessHotel is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantAccessHotel\"",
            "resource_type": "Hotel",
        },
    ]
