"""Verification plan for tags_report."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "update_workspace_safety",
            "description": "UpdateWorkspace is only permitted for Role-A members whose Role-A tags match the workspace tags",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"UpdateWorkspace\"",
            "resource_type": "Workspace",
            "reference_path": os.path.join(REFS, "ceiling_update_workspace.cedar"),
        },
        {
            "name": "delete_workspace_safety",
            "description": "DeleteWorkspace is only permitted for Role-A members whose Role-A tags match the workspace tags",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteWorkspace\"",
            "resource_type": "Workspace",
            "reference_path": os.path.join(REFS, "ceiling_delete_workspace.cedar"),
        },
        {
            "name": "read_workspace_safety",
            "description": "ReadWorkspace is only permitted for Role-A members with matching Role-A tags or Role-B members with matching Role-B tags",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ReadWorkspace\"",
            "resource_type": "Workspace",
            "reference_path": os.path.join(REFS, "ceiling_read_workspace.cedar"),
        },
        {
            "name": "generate_report_safety",
            "description": "generateReport is only permitted for Role-A members whose Role-A tags match the linked workspace tags",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"generateReport\"",
            "resource_type": "Report",
            "reference_path": os.path.join(REFS, "ceiling_generate_report.cedar"),
        },
        {
            "name": "view_report_safety",
            "description": "viewReport is only permitted for Role-A users with matching Role-A tags, or Role-B users with matching Role-B tags when the report is not confidential",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewReport\"",
            "resource_type": "Report",
            "reference_path": os.path.join(REFS, "ceiling_view_report.cedar"),
        },
        {
            "name": "role_a_update_floor",
            "description": "A Role-A member with the Role-A record present but no sub-tags defined must be able to UpdateWorkspace on a workspace with no tags",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"UpdateWorkspace\"",
            "resource_type": "Workspace",
            "floor_path": os.path.join(REFS, "floor_role_a_update.cedar"),
        },
        {
            "name": "role_a_delete_floor",
            "description": "A Role-A member with the Role-A record present but no sub-tags defined must be able to DeleteWorkspace on a workspace with no tags",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteWorkspace\"",
            "resource_type": "Workspace",
            "floor_path": os.path.join(REFS, "floor_role_a_delete.cedar"),
        },
        {
            "name": "role_b_read_floor",
            "description": "A Role-B member with the Role-B record present but no sub-tags must be able to ReadWorkspace on a workspace with no tags",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ReadWorkspace\"",
            "resource_type": "Workspace",
            "floor_path": os.path.join(REFS, "floor_role_b_read.cedar"),
        },
        {
            "name": "role_a_read_floor_with_all_wildcard",
            "description": "A Role-A member whose Role-A production_status contains ALL must be able to ReadWorkspace on a workspace whose production_status is any set when other tag groups are absent",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ReadWorkspace\"",
            "resource_type": "Workspace",
            "floor_path": os.path.join(REFS, "floor_role_a_read_all_wildcard.cedar"),
        },
        {
            "name": "role_a_generate_report_floor",
            "description": "A Role-A member with the Role-A record present but no sub-tags defined must be able to generateReport on a report linked to a workspace with no tags",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"generateReport\"",
            "resource_type": "Report",
            "floor_path": os.path.join(REFS, "floor_role_a_generate_report.cedar"),
        },
        {
            "name": "role_b_view_nonconf_report_floor",
            "description": "A Role-B member with the Role-B record present but no sub-tags defined must be able to view a non-confidential report linked to a workspace with no tags",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewReport\"",
            "resource_type": "Report",
            "floor_path": os.path.join(REFS, "floor_role_b_view_nonconf_report.cedar"),
        },
        {
            "name": "role_a_view_conf_report_floor",
            "description": "A Role-A member with matching Role-A tags must be able to view a confidential report",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewReport\"",
            "resource_type": "Report",
            "floor_path": os.path.join(REFS, "floor_role_a_view_conf_report.cedar"),
        },
        {
            "name": "liveness_update_workspace",
            "description": "UpdateWorkspace policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"UpdateWorkspace\"",
            "resource_type": "Workspace",
        },
        {
            "name": "liveness_delete_workspace",
            "description": "DeleteWorkspace policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"DeleteWorkspace\"",
            "resource_type": "Workspace",
        },
        {
            "name": "liveness_read_workspace",
            "description": "ReadWorkspace policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ReadWorkspace\"",
            "resource_type": "Workspace",
        },
        {
            "name": "liveness_generate_report",
            "description": "generateReport policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"generateReport\"",
            "resource_type": "Report",
        },
        {
            "name": "liveness_view_report",
            "description": "viewReport policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewReport\"",
            "resource_type": "Report",
        },
    ]
