"""Verification plan for github_release."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "pull_safety",
            "description": "Pull access only for users who are readers of the repository",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"pull\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_pull.cedar"),
        },
        {
            "name": "fork_safety",
            "description": "Fork access only for users who are readers of the repository",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"fork\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_fork.cedar"),
        },
        {
            "name": "push_safety",
            "description": "Push access only for writers, and blocked if repo is archived",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"push\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_push.cedar"),
        },
        {
            "name": "edit_issue_safety",
            "description": "Edit issue only if reader-reporter or writer of the issue's repo",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"edit_issue\"",
            "resource_type": "Issue",
            "reference_path": os.path.join(REFS, "ceiling_edit_issue.cedar"),
        },
        {
            "name": "delete_issue_safety",
            "description": "Delete issue only if reader-reporter or maintainer of the issue's repo",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"delete_issue\"",
            "resource_type": "Issue",
            "reference_path": os.path.join(REFS, "ceiling_delete_issue.cedar"),
        },
        {
            "name": "assign_issue_safety",
            "description": "Assign issue only for triagers of the issue's repo",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"assign_issue\"",
            "resource_type": "Issue",
            "reference_path": os.path.join(REFS, "ceiling_assign_issue.cedar"),
        },
        {
            "name": "add_reader_safety",
            "description": "Add reader only for admins, blocked if repo is archived",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"add_reader\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_add_reader.cedar"),
        },
        {
            "name": "add_writer_safety",
            "description": "Add writer only for admins, blocked if repo is archived",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"add_writer\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_add_writer.cedar"),
        },
        {
            "name": "add_maintainer_safety",
            "description": "Add maintainer only for admins, blocked if repo is archived",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"add_maintainer\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_add_maintainer.cedar"),
        },
        {
            "name": "add_admin_safety",
            "description": "Add admin only for admins, blocked if repo is archived",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"add_admin\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_add_admin.cedar"),
        },
        {
            "name": "add_triager_safety",
            "description": "Add triager only for admins, blocked if repo is archived",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"add_triager\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_add_triager.cedar"),
        },
        {
            "name": "create_release_safety",
            "description": "Create release only for maintainers or admins of the release repo",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"create_release\"",
            "resource_type": "Release",
            "reference_path": os.path.join(REFS, "ceiling_create_release.cedar"),
        },
        {
            "name": "delete_release_safety",
            "description": "Delete release only for non-author maintainers or admins of the release repo",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"delete_release\"",
            "resource_type": "Release",
            "reference_path": os.path.join(REFS, "ceiling_delete_release.cedar"),
        },
        {
            "name": "reader_pull_floor",
            "description": "Readers MUST be able to pull from a repository, including archived repos",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"pull\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_reader_pull.cedar"),
        },
        {
            "name": "reader_fork_floor",
            "description": "Readers MUST be able to fork a repository, including archived repos",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"fork\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_reader_fork.cedar"),
        },
        {
            "name": "writer_push_floor",
            "description": "Writers MUST be able to push to a non-archived repository",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"push\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_writer_push.cedar"),
        },
        {
            "name": "writer_edit_issue_floor",
            "description": "Writers MUST be able to edit any issue in their repo regardless of reporter",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"edit_issue\"",
            "resource_type": "Issue",
            "floor_path": os.path.join(REFS, "floor_writer_edit_issue.cedar"),
        },
        {
            "name": "reporter_edit_issue_floor",
            "description": "Readers who are the reporter MUST be able to edit their own issue",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"edit_issue\"",
            "resource_type": "Issue",
            "floor_path": os.path.join(REFS, "floor_reporter_edit_issue.cedar"),
        },
        {
            "name": "reporter_delete_issue_floor",
            "description": "Readers who are the reporter MUST be able to delete their own issue",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"delete_issue\"",
            "resource_type": "Issue",
            "floor_path": os.path.join(REFS, "floor_reporter_delete_issue.cedar"),
        },
        {
            "name": "maintainer_delete_issue_floor",
            "description": "Maintainers MUST be able to delete any issue in their repo",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"delete_issue\"",
            "resource_type": "Issue",
            "floor_path": os.path.join(REFS, "floor_maintainer_delete_issue.cedar"),
        },
        {
            "name": "triager_assign_issue_floor",
            "description": "Triagers MUST be able to assign issues in their repo",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"assign_issue\"",
            "resource_type": "Issue",
            "floor_path": os.path.join(REFS, "floor_triager_assign_issue.cedar"),
        },
        {
            "name": "admin_add_reader_floor",
            "description": "Admins MUST be able to add_reader on non-archived repos",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"add_reader\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_admin_add_reader.cedar"),
        },
        {
            "name": "admin_add_writer_floor",
            "description": "Admins MUST be able to add_writer on non-archived repos",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"add_writer\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_admin_add_writer.cedar"),
        },
        {
            "name": "admin_add_maintainer_floor",
            "description": "Admins MUST be able to add_maintainer on non-archived repos",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"add_maintainer\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_admin_add_maintainer.cedar"),
        },
        {
            "name": "admin_add_admin_floor",
            "description": "Admins MUST be able to add_admin on non-archived repos",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"add_admin\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_admin_add_admin.cedar"),
        },
        {
            "name": "admin_add_triager_floor",
            "description": "Admins MUST be able to add_triager on non-archived repos",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"add_triager\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_admin_add_triager.cedar"),
        },
        {
            "name": "maintainer_create_release_floor",
            "description": "Maintainers MUST be able to create releases in their repo",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"create_release\"",
            "resource_type": "Release",
            "floor_path": os.path.join(REFS, "floor_maintainer_create_release.cedar"),
        },
        {
            "name": "admin_delete_release_floor",
            "description": "Admins who are not the author MUST be able to delete releases in their repo",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"delete_release\"",
            "resource_type": "Release",
            "floor_path": os.path.join(REFS, "floor_admin_delete_release.cedar"),
        },
        {
            "name": "liveness_pull",
            "description": "Pull policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"pull\"",
            "resource_type": "Repository",
        },
        {
            "name": "liveness_push",
            "description": "Push policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"push\"",
            "resource_type": "Repository",
        },
        {
            "name": "liveness_fork",
            "description": "Fork policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"fork\"",
            "resource_type": "Repository",
        },
        {
            "name": "liveness_edit_issue",
            "description": "Edit issue policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"edit_issue\"",
            "resource_type": "Issue",
        },
        {
            "name": "liveness_delete_issue",
            "description": "Delete issue policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"delete_issue\"",
            "resource_type": "Issue",
        },
        {
            "name": "liveness_assign_issue",
            "description": "Assign issue policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"assign_issue\"",
            "resource_type": "Issue",
        },
        {
            "name": "liveness_add_reader",
            "description": "Add reader policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"add_reader\"",
            "resource_type": "Repository",
        },
        {
            "name": "liveness_add_writer",
            "description": "Add writer policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"add_writer\"",
            "resource_type": "Repository",
        },
        {
            "name": "liveness_add_maintainer",
            "description": "Add maintainer policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"add_maintainer\"",
            "resource_type": "Repository",
        },
        {
            "name": "liveness_add_admin",
            "description": "Add admin policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"add_admin\"",
            "resource_type": "Repository",
        },
        {
            "name": "liveness_add_triager",
            "description": "Add triager policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"add_triager\"",
            "resource_type": "Repository",
        },
        {
            "name": "liveness_create_release",
            "description": "Create release policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"create_release\"",
            "resource_type": "Release",
        },
        {
            "name": "liveness_delete_release",
            "description": "Delete release policy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"delete_release\"",
            "resource_type": "Release",
        },
    ]
