"""Verification plan for streaming_content_rating."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "ceiling_freemember_watch_movie",
            "description": "FreeMember may watch a Movie only when it is free and not NC-17",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "ceiling_freemember_watch_movie.cedar"),
        },
        {
            "name": "ceiling_freemember_watch_show",
            "description": "FreeMember may watch a Show only when it is free and not NC-17",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "reference_path": os.path.join(REFS, "ceiling_freemember_watch_show.cedar"),
        },
        {
            "name": "ceiling_subscriber_watch_movie",
            "description": "Subscriber may watch a Movie only when it does not require rent or buy, kid bedtime does not apply, and content rating constraints are satisfied",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "ceiling_subscriber_watch_movie.cedar"),
        },
        {
            "name": "ceiling_subscriber_watch_show",
            "description": "Subscriber may watch a Show only when release timing is allowed, kid bedtime does not apply, and content rating constraints are satisfied",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "reference_path": os.path.join(REFS, "ceiling_subscriber_watch_show.cedar"),
        },
        {
            "name": "ceiling_freemember_rent_movie",
            "description": "FreeMember can never rent a Movie",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"rent\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "ceiling_freemember_rent_movie.cedar"),
        },
        {
            "name": "ceiling_subscriber_rent_movie",
            "description": "Subscriber may rent a Movie only when it is Oscar-nominated and inside the promo window",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"rent\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "ceiling_subscriber_rent_movie.cedar"),
        },
        {
            "name": "ceiling_freemember_buy_movie",
            "description": "FreeMember can never buy a Movie",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"buy\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "ceiling_freemember_buy_movie.cedar"),
        },
        {
            "name": "ceiling_subscriber_buy_movie",
            "description": "Subscriber may buy a Movie only when it is Oscar-nominated and inside the promo window",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"buy\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "ceiling_subscriber_buy_movie.cedar"),
        },
        {
            "name": "floor_freemember_watch_free_movie_non_nc17",
            "description": "FreeMember must be able to watch a free non-NC-17 Movie",
            "type": "floor",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "floor_freemember_watch_free_movie_non_nc17.cedar"),
        },
        {
            "name": "floor_freemember_watch_free_show_non_nc17",
            "description": "FreeMember must be able to watch a free non-NC-17 Show",
            "type": "floor",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "floor_path": os.path.join(REFS, "floor_freemember_watch_free_show_non_nc17.cedar"),
        },
        {
            "name": "floor_subscriber_watch_movie_rated_r_adult",
            "description": "An adult Subscriber must be able to watch an R-rated Movie that does not require rent or buy outside kid bedtime",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "floor_subscriber_watch_movie_rated_r_adult.cedar"),
        },
        {
            "name": "floor_subscriber_watch_show_released_r_adult",
            "description": "An adult Subscriber must be able to watch a released R-rated Show outside kid bedtime",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "floor_path": os.path.join(REFS, "floor_subscriber_watch_show_released_r_adult.cedar"),
        },
        {
            "name": "floor_premium_watch_show_early_nc17_adult",
            "description": "An adult premium Subscriber must be able to watch an early-access NC-17 Show within 24 hours before release outside kid bedtime",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "floor_path": os.path.join(REFS, "floor_premium_watch_show_early_nc17_adult.cedar"),
        },
        {
            "name": "floor_premium_watch_movie_nc17_adult",
            "description": "An adult premium Subscriber must be able to watch an NC-17 Movie that does not require rent or buy outside kid bedtime",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "floor_premium_watch_movie_nc17_adult.cedar"),
        },
        {
            "name": "floor_premium_watch_show_nc17_released_adult",
            "description": "An adult premium Subscriber must be able to watch a released NC-17 Show outside kid bedtime",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "floor_path": os.path.join(REFS, "floor_premium_watch_show_nc17_released_adult.cedar"),
        },
        {
            "name": "floor_subscriber_rent_movie",
            "description": "Subscriber must be able to rent an Oscar-nominated Movie inside the promo window",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"rent\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "floor_subscriber_rent_movie.cedar"),
        },
        {
            "name": "floor_subscriber_buy_movie",
            "description": "Subscriber must be able to buy an Oscar-nominated Movie inside the promo window",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"buy\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "floor_subscriber_buy_movie.cedar"),
        },
        {
            "name": "liveness_freemember_watch_movie",
            "description": "FreeMember watch Movie is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
        },
        {
            "name": "liveness_freemember_watch_show",
            "description": "FreeMember watch Show is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
        },
        {
            "name": "liveness_subscriber_watch_movie",
            "description": "Subscriber watch Movie is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
        },
        {
            "name": "liveness_subscriber_watch_show",
            "description": "Subscriber watch Show is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
        },
        {
            "name": "liveness_subscriber_rent_movie",
            "description": "Subscriber rent Movie is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"rent\"",
            "resource_type": "Movie",
        },
        {
            "name": "liveness_subscriber_buy_movie",
            "description": "Subscriber buy Movie is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"buy\"",
            "resource_type": "Movie",
        },
    ]
