"""Verification plan for sales_contract."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "view_presentation_safety",
            "description": "viewPresentation is only permitted for internal users or users in the presentation viewers or editors set",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_viewPresentation.cedar"),
        },
        {
            "name": "remove_self_presentation_safety",
            "description": "removeSelfAccessFromPresentation is only permitted for users in the presentation viewers or editors set",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_removeSelfAccessFromPresentation.cedar"),
        },
        {
            "name": "duplicate_presentation_safety",
            "description": "duplicatePresentation is only permitted for internal users or users in the presentation editors set",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_duplicatePresentation.cedar"),
        },
        {
            "name": "edit_presentation_safety",
            "description": "editPresentation is only permitted for internal users or non-customer users in the presentation editors set",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_editPresentation.cedar"),
        },
        {
            "name": "grant_view_presentation_safety",
            "description": "grantViewAccessToPresentation is only permitted for presentation editors and only for targets already in the viewers or editors set",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_grantViewAccessToPresentation.cedar"),
        },
        {
            "name": "grant_edit_presentation_safety",
            "description": "grantEditAccessToPresentation is only permitted for presentation editors and only for targets already in the editors set",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_grantEditAccessToPresentation.cedar"),
        },
        {
            "name": "view_template_safety",
            "description": "viewTemplate is only permitted for internal users, direct viewers, or users in viewerMarkets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_viewTemplate.cedar"),
        },
        {
            "name": "duplicate_template_safety",
            "description": "duplicateTemplate is only permitted for internal users, direct viewers, or users in viewerMarkets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"duplicateTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_duplicateTemplate.cedar"),
        },
        {
            "name": "remove_self_template_safety",
            "description": "removeSelfAccessFromTemplate is deny-by-default in this scenario",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_removeSelfAccessFromTemplate.cedar"),
        },
        {
            "name": "edit_template_safety",
            "description": "editTemplate is only permitted for internal users or non-customer users in the template editors set",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_editTemplate.cedar"),
        },
        {
            "name": "remove_others_template_safety",
            "description": "removeOthersAccessToTemplate is only permitted for non-customer users in the template editors set",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeOthersAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_removeOthersAccessToTemplate.cedar"),
        },
        {
            "name": "grant_view_template_safety",
            "description": "grantViewAccessToTemplate is deny-by-default in this scenario",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_grantViewAccessToTemplate.cedar"),
        },
        {
            "name": "grant_edit_template_safety",
            "description": "grantEditAccessToTemplate is deny-by-default in this scenario",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_grantEditAccessToTemplate.cedar"),
        },
        {
            "name": "view_contract_safety",
            "description": "viewContract is only permitted for internal users or non-customer users who are editors of the linked presentation",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewContract\"",
            "resource_type": "Contract",
            "reference_path": os.path.join(REFS, "ceiling_viewContract.cedar"),
        },
        {
            "name": "sign_contract_safety",
            "description": "signContract is only permitted for internal users on unsigned contracts",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"signContract\"",
            "resource_type": "Contract",
            "reference_path": os.path.join(REFS, "ceiling_signContract.cedar"),
        },
        {
            "name": "internal_view_presentation_floor",
            "description": "Internal users must be able to view any presentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_internal_viewPresentation.cedar"),
        },
        {
            "name": "viewer_remove_self_presentation_floor",
            "description": "Users in the presentation viewers set must be able to remove their own presentation access",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_viewer_removeSelfAccessFromPresentation.cedar"),
        },
        {
            "name": "editor_duplicate_presentation_floor",
            "description": "Non-internal presentation editors must be able to duplicate a presentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_editor_duplicatePresentation.cedar"),
        },
        {
            "name": "editor_edit_presentation_floor",
            "description": "Non-customer presentation editors must be able to edit a presentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_editor_editPresentation.cedar"),
        },
        {
            "name": "editor_grant_view_presentation_floor",
            "description": "Presentation editors must be able to grant viewer access for targets already in viewers",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_editor_grantViewAccessToPresentation.cedar"),
        },
        {
            "name": "editor_grant_edit_presentation_floor",
            "description": "Presentation editors must be able to grant editor access for targets already in editors",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_editor_grantEditAccessToPresentation.cedar"),
        },
        {
            "name": "internal_view_template_floor",
            "description": "Internal users must be able to view any template",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_internal_viewTemplate.cedar"),
        },
        {
            "name": "market_duplicate_template_floor",
            "description": "Users in a template viewer market must be able to duplicate that template",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"duplicateTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_market_duplicateTemplate.cedar"),
        },
        {
            "name": "editor_edit_template_floor",
            "description": "Non-customer template editors must be able to edit a template",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_editor_editTemplate.cedar"),
        },
        {
            "name": "editor_remove_others_template_floor",
            "description": "Non-customer template editors must be able to remove others' template access",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"removeOthersAccessToTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_editor_removeOthersAccessToTemplate.cedar"),
        },
        {
            "name": "editor_view_contract_floor",
            "description": "Non-customer editors of the linked presentation must be able to view a contract",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewContract\"",
            "resource_type": "Contract",
            "floor_path": os.path.join(REFS, "floor_editor_viewContract.cedar"),
        },
        {
            "name": "internal_sign_contract_floor",
            "description": "Internal users must be able to sign unsigned contracts",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"signContract\"",
            "resource_type": "Contract",
            "floor_path": os.path.join(REFS, "floor_internal_signContract.cedar"),
        },
        {
            "name": "liveness_viewPresentation",
            "description": "viewPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_removeSelfAccessFromPresentation",
            "description": "removeSelfAccessFromPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_duplicatePresentation",
            "description": "duplicatePresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_editPresentation",
            "description": "editPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_grantViewAccessToPresentation",
            "description": "grantViewAccessToPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_grantEditAccessToPresentation",
            "description": "grantEditAccessToPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_viewTemplate",
            "description": "viewTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_duplicateTemplate",
            "description": "duplicateTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"duplicateTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_editTemplate",
            "description": "editTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_removeOthersAccessToTemplate",
            "description": "removeOthersAccessToTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"removeOthersAccessToTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_viewContract",
            "description": "viewContract is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewContract\"",
            "resource_type": "Contract",
        },
        {
            "name": "liveness_signContract",
            "description": "signContract is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"signContract\"",
            "resource_type": "Contract",
        },
    ]
