"""Verification plan for github_deploy_env."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "ceiling_pull",
            "description": "Pull is only allowed for repository readers",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"pull\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_pull.cedar"),
        },
        {
            "name": "ceiling_fork",
            "description": "Fork is only allowed for repository readers",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"fork\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_fork.cedar"),
        },
        {
            "name": "ceiling_push",
            "description": "Push is only allowed for writers on non-archived repositories",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"push\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_push.cedar"),
        },
        {
            "name": "ceiling_assign_issue",
            "description": "Assign issue is only allowed for triagers of the issue repository",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"assign_issue\"",
            "resource_type": "Issue",
            "reference_path": os.path.join(REFS, "ceiling_assign_issue.cedar"),
        },
        {
            "name": "ceiling_edit_issue",
            "description": "Edit issue is only allowed for the reporter with reader access or any writer",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"edit_issue\"",
            "resource_type": "Issue",
            "reference_path": os.path.join(REFS, "ceiling_edit_issue.cedar"),
        },
        {
            "name": "ceiling_delete_issue",
            "description": "Delete issue is only allowed for the reporter with reader access or any maintainer",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"delete_issue\"",
            "resource_type": "Issue",
            "reference_path": os.path.join(REFS, "ceiling_delete_issue.cedar"),
        },
        {
            "name": "ceiling_add_reader",
            "description": "Add reader is only allowed for admins on non-archived repositories",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"add_reader\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_add_reader.cedar"),
        },
        {
            "name": "ceiling_add_writer",
            "description": "Add writer is only allowed for admins on non-archived repositories",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"add_writer\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_add_writer.cedar"),
        },
        {
            "name": "ceiling_add_maintainer",
            "description": "Add maintainer is only allowed for admins on non-archived repositories",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"add_maintainer\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_add_maintainer.cedar"),
        },
        {
            "name": "ceiling_add_admin",
            "description": "Add admin is only allowed for admins on non-archived repositories",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"add_admin\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_add_admin.cedar"),
        },
        {
            "name": "ceiling_add_triager",
            "description": "Add triager is only allowed for admins on non-archived repositories",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"add_triager\"",
            "resource_type": "Repository",
            "reference_path": os.path.join(REFS, "ceiling_add_triager.cedar"),
        },
        {
            "name": "ceiling_deploy",
            "description": "Deploy is only allowed for maintainers or admins, and production deploys are blocked on archived repositories",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"deploy\"",
            "resource_type": "Deployment",
            "reference_path": os.path.join(REFS, "ceiling_deploy.cedar"),
        },
        {
            "name": "floor_reader_pull",
            "description": "Readers must be able to pull repositories",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"pull\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_reader_pull.cedar"),
        },
        {
            "name": "floor_reader_fork",
            "description": "Readers must be able to fork repositories",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"fork\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_reader_fork.cedar"),
        },
        {
            "name": "floor_writer_push",
            "description": "Writers must be able to push to non-archived repositories",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"push\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_writer_push.cedar"),
        },
        {
            "name": "floor_triager_assign_issue",
            "description": "Triagers must be able to assign issues",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"assign_issue\"",
            "resource_type": "Issue",
            "floor_path": os.path.join(REFS, "floor_triager_assign_issue.cedar"),
        },
        {
            "name": "floor_reporter_edit_issue",
            "description": "Readers who reported an issue must be able to edit it",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"edit_issue\"",
            "resource_type": "Issue",
            "floor_path": os.path.join(REFS, "floor_reporter_edit_issue.cedar"),
        },
        {
            "name": "floor_writer_edit_issue",
            "description": "Writers must be able to edit any issue in their repository",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"edit_issue\"",
            "resource_type": "Issue",
            "floor_path": os.path.join(REFS, "floor_writer_edit_issue.cedar"),
        },
        {
            "name": "floor_reporter_delete_issue",
            "description": "Readers who reported an issue must be able to delete it",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"delete_issue\"",
            "resource_type": "Issue",
            "floor_path": os.path.join(REFS, "floor_reporter_delete_issue.cedar"),
        },
        {
            "name": "floor_maintainer_delete_issue",
            "description": "Maintainers must be able to delete any issue in their repository",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"delete_issue\"",
            "resource_type": "Issue",
            "floor_path": os.path.join(REFS, "floor_maintainer_delete_issue.cedar"),
        },
        {
            "name": "floor_admin_add_reader",
            "description": "Admins must be able to add readers on non-archived repositories",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"add_reader\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_admin_add_reader.cedar"),
        },
        {
            "name": "floor_admin_add_writer",
            "description": "Admins must be able to add writers on non-archived repositories",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"add_writer\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_admin_add_writer.cedar"),
        },
        {
            "name": "floor_admin_add_maintainer",
            "description": "Admins must be able to add maintainers on non-archived repositories",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"add_maintainer\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_admin_add_maintainer.cedar"),
        },
        {
            "name": "floor_admin_add_admin",
            "description": "Admins must be able to add admins on non-archived repositories",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"add_admin\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_admin_add_admin.cedar"),
        },
        {
            "name": "floor_admin_add_triager",
            "description": "Admins must be able to add triagers on non-archived repositories",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"add_triager\"",
            "resource_type": "Repository",
            "floor_path": os.path.join(REFS, "floor_admin_add_triager.cedar"),
        },
        {
            "name": "floor_maintainer_deploy_staging",
            "description": "Maintainers must be able to deploy to staging even on archived repositories",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"deploy\"",
            "resource_type": "Deployment",
            "floor_path": os.path.join(REFS, "floor_maintainer_deploy_staging.cedar"),
        },
        {
            "name": "floor_admin_deploy_production_non_archived",
            "description": "Admins must be able to deploy to production when the repository is not archived",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"deploy\"",
            "resource_type": "Deployment",
            "floor_path": os.path.join(REFS, "floor_admin_deploy_production_non_archived.cedar"),
        },
        {
            "name": "liveness_pull",
            "description": "Pull is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"pull\"",
            "resource_type": "Repository",
        },
        {
            "name": "liveness_fork",
            "description": "Fork is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"fork\"",
            "resource_type": "Repository",
        },
        {
            "name": "liveness_push",
            "description": "Push is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"push\"",
            "resource_type": "Repository",
        },
        {
            "name": "liveness_assign_issue",
            "description": "Assign issue is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"assign_issue\"",
            "resource_type": "Issue",
        },
        {
            "name": "liveness_edit_issue",
            "description": "Edit issue is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"edit_issue\"",
            "resource_type": "Issue",
        },
        {
            "name": "liveness_delete_issue",
            "description": "Delete issue is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"delete_issue\"",
            "resource_type": "Issue",
        },
        {
            "name": "liveness_add_reader",
            "description": "Add reader is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"add_reader\"",
            "resource_type": "Repository",
        },
        {
            "name": "liveness_add_writer",
            "description": "Add writer is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"add_writer\"",
            "resource_type": "Repository",
        },
        {
            "name": "liveness_add_maintainer",
            "description": "Add maintainer is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"add_maintainer\"",
            "resource_type": "Repository",
        },
        {
            "name": "liveness_add_admin",
            "description": "Add admin is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"add_admin\"",
            "resource_type": "Repository",
        },
        {
            "name": "liveness_add_triager",
            "description": "Add triager is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"add_triager\"",
            "resource_type": "Repository",
        },
        {
            "name": "liveness_deploy",
            "description": "Deploy is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"deploy\"",
            "resource_type": "Deployment",
        },
    ]
