"""Verification plan for sales_fiscal_window."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "ceiling_viewPresentation",
            "description": "viewPresentation is only permitted for internal users or non-internal users in the presentation viewers or editors sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_viewPresentation.cedar"),
        },
        {
            "name": "ceiling_removeSelfAccessFromPresentation",
            "description": "removeSelfAccessFromPresentation is only permitted for non-internal users in the presentation viewers or editors sets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_removeSelfAccessFromPresentation.cedar"),
        },
        {
            "name": "ceiling_duplicatePresentation",
            "description": "duplicatePresentation is only permitted for internal users or non-internal users in the presentation editors set",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_duplicatePresentation.cedar"),
        },
        {
            "name": "ceiling_editPresentation_fiscal_window",
            "description": "editPresentation is only permitted for internal users or for non-customer editors whose presentation fiscal year matches the current year",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_editPresentation_fiscal_window.cedar"),
        },
        {
            "name": "ceiling_grantViewAccessToPresentation",
            "description": "grantViewAccessToPresentation is only permitted for non-internal presentation editors, limited to targets already in viewers or editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_grantViewAccessToPresentation.cedar"),
        },
        {
            "name": "ceiling_grantEditAccessToPresentation",
            "description": "grantEditAccessToPresentation is only permitted for non-internal presentation editors, limited to targets already in editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_grantEditAccessToPresentation.cedar"),
        },
        {
            "name": "ceiling_viewTemplate",
            "description": "viewTemplate is only permitted for internal users or non-internal users in the template viewers set or viewerMarkets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_viewTemplate.cedar"),
        },
        {
            "name": "ceiling_duplicateTemplate",
            "description": "duplicateTemplate is only permitted for internal users or non-internal users in the template viewers set or viewerMarkets",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"duplicateTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_duplicateTemplate.cedar"),
        },
        {
            "name": "ceiling_removeSelfAccessFromTemplate",
            "description": "removeSelfAccessFromTemplate is never permitted by the specification",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_removeSelfAccessFromTemplate.cedar"),
        },
        {
            "name": "ceiling_editTemplate_fiscal_window",
            "description": "editTemplate is only permitted for internal users or for non-customer template editors whose current year matches the host current year",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_editTemplate_fiscal_window.cedar"),
        },
        {
            "name": "ceiling_removeOthersAccessToTemplate",
            "description": "removeOthersAccessToTemplate is only permitted for non-internal users in the template editors set",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeOthersAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_removeOthersAccessToTemplate.cedar"),
        },
        {
            "name": "ceiling_grantViewAccessToTemplate",
            "description": "grantViewAccessToTemplate is never permitted by the specification",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_grantViewAccessToTemplate.cedar"),
        },
        {
            "name": "ceiling_grantEditAccessToTemplate",
            "description": "grantEditAccessToTemplate is never permitted by the specification",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_grantEditAccessToTemplate.cedar"),
        },
        {
            "name": "floor_internal_viewPresentation",
            "description": "An internal user must be able to viewPresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_internal_viewPresentation.cedar"),
        },
        {
            "name": "floor_noninternal_viewer_viewPresentation",
            "description": "A non-internal viewer must be able to viewPresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_noninternal_viewer_viewPresentation.cedar"),
        },
        {
            "name": "floor_noninternal_viewer_removeSelfAccessFromPresentation",
            "description": "A non-internal viewer must be able to removeSelfAccessFromPresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_noninternal_viewer_removeSelfAccessFromPresentation.cedar"),
        },
        {
            "name": "floor_internal_duplicatePresentation",
            "description": "An internal user must be able to duplicatePresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_internal_duplicatePresentation.cedar"),
        },
        {
            "name": "floor_noncustomer_editor_currentyear_editPresentation",
            "description": "A non-customer non-internal editor must be able to editPresentation when the fiscal year matches the current year",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_noncustomer_editor_currentyear_editPresentation.cedar"),
        },
        {
            "name": "floor_editor_targeted_grantViewAccessToPresentation",
            "description": "A non-internal editor must be able to grantViewAccessToPresentation when the target is already in viewers",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_editor_targeted_grantViewAccessToPresentation.cedar"),
        },
        {
            "name": "floor_editor_targeted_grantEditAccessToPresentation",
            "description": "A non-internal editor must be able to grantEditAccessToPresentation when the target is already in editors",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_editor_targeted_grantEditAccessToPresentation.cedar"),
        },
        {
            "name": "floor_internal_viewTemplate",
            "description": "An internal user must be able to viewTemplate",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_internal_viewTemplate.cedar"),
        },
        {
            "name": "floor_noninternal_market_viewer_viewTemplate",
            "description": "A non-internal user in a viewer market must be able to viewTemplate",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_noninternal_market_viewer_viewTemplate.cedar"),
        },
        {
            "name": "floor_internal_duplicateTemplate",
            "description": "An internal user must be able to duplicateTemplate",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"duplicateTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_internal_duplicateTemplate.cedar"),
        },
        {
            "name": "floor_noncustomer_editor_currentyear_editTemplate",
            "description": "A non-customer non-internal editor must be able to editTemplate when the current year matches the fiscal year",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_noncustomer_editor_currentyear_editTemplate.cedar"),
        },
        {
            "name": "floor_noninternal_editor_removeOthersAccessToTemplate",
            "description": "A non-internal editor must be able to removeOthersAccessToTemplate",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"removeOthersAccessToTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_noninternal_editor_removeOthersAccessToTemplate.cedar"),
        },
        {
            "name": "liveness_viewPresentation",
            "description": "viewPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_removeSelfAccessFromPresentation",
            "description": "removeSelfAccessFromPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_duplicatePresentation",
            "description": "duplicatePresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_editPresentation",
            "description": "editPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_grantViewAccessToPresentation",
            "description": "grantViewAccessToPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_grantEditAccessToPresentation",
            "description": "grantEditAccessToPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_viewTemplate",
            "description": "viewTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_duplicateTemplate",
            "description": "duplicateTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"duplicateTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_editTemplate",
            "description": "editTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_removeOthersAccessToTemplate",
            "description": "removeOthersAccessToTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"removeOthersAccessToTemplate\"",
            "resource_type": "Template",
        },
    ]
