"""Verification plan for sales_territory."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "ceiling_viewPresentation",
            "description": "viewPresentation is only permitted for internal users, or for non-internal users in the presentation territory who are in viewers or editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_viewPresentation.cedar"),
        },
        {
            "name": "ceiling_duplicatePresentation",
            "description": "duplicatePresentation is only permitted for internal users or non-internal editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_duplicatePresentation.cedar"),
        },
        {
            "name": "ceiling_editPresentation",
            "description": "editPresentation is only permitted for internal users, or for non-customer non-internal editors in the presentation territory",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_editPresentation.cedar"),
        },
        {
            "name": "ceiling_removeSelfAccessFromPresentation",
            "description": "removeSelfAccessFromPresentation is only permitted for internal users or non-internal users in viewers or editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_removeSelfAccessFromPresentation.cedar"),
        },
        {
            "name": "ceiling_grantViewAccessToPresentation",
            "description": "grantViewAccessToPresentation is only permitted for presentation editors, and the target must already be in viewers or editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_grantViewAccessToPresentation.cedar"),
        },
        {
            "name": "ceiling_grantEditAccessToPresentation",
            "description": "grantEditAccessToPresentation is only permitted for presentation editors, and the target must already be in editors",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
            "reference_path": os.path.join(REFS, "ceiling_grantEditAccessToPresentation.cedar"),
        },
        {
            "name": "ceiling_viewTemplate",
            "description": "viewTemplate is only permitted for internal users, or for non-internal users directly listed or in a viewer market",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_viewTemplate.cedar"),
        },
        {
            "name": "ceiling_duplicateTemplate",
            "description": "duplicateTemplate is only permitted for internal users, or for non-internal users directly listed or in a viewer market",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"duplicateTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_duplicateTemplate.cedar"),
        },
        {
            "name": "ceiling_removeSelfAccessFromTemplate",
            "description": "removeSelfAccessFromTemplate is only permitted for internal users, or for non-internal users directly listed as viewer or editor",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_removeSelfAccessFromTemplate.cedar"),
        },
        {
            "name": "ceiling_editTemplate",
            "description": "editTemplate is only permitted for internal users, or for non-customer non-internal users directly listed as editor",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_editTemplate.cedar"),
        },
        {
            "name": "ceiling_removeOthersAccessToTemplate",
            "description": "removeOthersAccessToTemplate is only permitted for internal users, or for non-internal users directly listed as editor",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"removeOthersAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_removeOthersAccessToTemplate.cedar"),
        },
        {
            "name": "ceiling_grantViewAccessToTemplate",
            "description": "grantViewAccessToTemplate is only permitted for internal users",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_grantViewAccessToTemplate.cedar"),
        },
        {
            "name": "ceiling_grantEditAccessToTemplate",
            "description": "grantEditAccessToTemplate is only permitted for internal users and any target user must be internal",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToTemplate\"",
            "resource_type": "Template",
            "reference_path": os.path.join(REFS, "ceiling_grantEditAccessToTemplate.cedar"),
        },
        {
            "name": "floor_internal_viewPresentation",
            "description": "An internal user must be able to viewPresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_internal_viewPresentation.cedar"),
        },
        {
            "name": "floor_internal_editPresentation",
            "description": "An internal user must be able to editPresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_internal_editPresentation.cedar"),
        },
        {
            "name": "floor_external_viewer_viewPresentation_same_territory",
            "description": "A non-internal viewer in the matching territory must be able to viewPresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_external_viewer_viewPresentation_same_territory.cedar"),
        },
        {
            "name": "floor_external_editor_editPresentation_same_territory",
            "description": "A distributor editor in the matching territory must be able to editPresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_external_editor_editPresentation_same_territory.cedar"),
        },
        {
            "name": "floor_external_editor_duplicatePresentation",
            "description": "A non-internal editor must be able to duplicatePresentation",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
            "floor_path": os.path.join(REFS, "floor_external_editor_duplicatePresentation.cedar"),
        },
        {
            "name": "floor_internal_viewTemplate",
            "description": "An internal user must be able to viewTemplate",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_internal_viewTemplate.cedar"),
        },
        {
            "name": "floor_market_viewer_viewTemplate",
            "description": "A non-internal user in a viewer market must be able to viewTemplate",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_market_viewer_viewTemplate.cedar"),
        },
        {
            "name": "floor_external_editor_editTemplate",
            "description": "A distributor editor must be able to editTemplate",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
            "floor_path": os.path.join(REFS, "floor_external_editor_editTemplate.cedar"),
        },
        {
            "name": "liveness_viewPresentation",
            "description": "viewPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_duplicatePresentation",
            "description": "duplicatePresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"duplicatePresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_editPresentation",
            "description": "editPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"editPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_removeSelfAccessFromPresentation",
            "description": "removeSelfAccessFromPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_grantViewAccessToPresentation",
            "description": "grantViewAccessToPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_grantEditAccessToPresentation",
            "description": "grantEditAccessToPresentation is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToPresentation\"",
            "resource_type": "Presentation",
        },
        {
            "name": "liveness_viewTemplate",
            "description": "viewTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"viewTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_duplicateTemplate",
            "description": "duplicateTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"duplicateTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_removeSelfAccessFromTemplate",
            "description": "removeSelfAccessFromTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"removeSelfAccessFromTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_editTemplate",
            "description": "editTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"editTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_removeOthersAccessToTemplate",
            "description": "removeOthersAccessToTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"removeOthersAccessToTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_grantViewAccessToTemplate",
            "description": "grantViewAccessToTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantViewAccessToTemplate\"",
            "resource_type": "Template",
        },
        {
            "name": "liveness_grantEditAccessToTemplate",
            "description": "grantEditAccessToTemplate is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"grantEditAccessToTemplate\"",
            "resource_type": "Template",
        },
    ]
