"""Verification plan for tags_role_d."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "ceiling_updateworkspace_roles_a_or_d",
            "description": "UpdateWorkspace is only permitted for Role-A or Role-D users whose tags match for that role",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"UpdateWorkspace\"",
            "resource_type": "Workspace",
            "reference_path": os.path.join(REFS, "ceiling_updateworkspace_roles_a_or_d.cedar"),
        },
        {
            "name": "ceiling_deleteworkspace_role_a",
            "description": "DeleteWorkspace is only permitted for Role-A users whose Role-A tags match",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"DeleteWorkspace\"",
            "resource_type": "Workspace",
            "reference_path": os.path.join(REFS, "ceiling_deleteworkspace_role_a.cedar"),
        },
        {
            "name": "ceiling_readworkspace_role_a_or_b",
            "description": "ReadWorkspace is only permitted for Role-A or Role-B users whose tags match for that role",
            "type": "implies",
            "principal_type": "User",
            "action": "Action::\"ReadWorkspace\"",
            "resource_type": "Workspace",
            "reference_path": os.path.join(REFS, "ceiling_readworkspace_role_a_or_b.cedar"),
        },
        {
            "name": "floor_updateworkspace_role_a",
            "description": "A Role-A user with matching tags must be able to UpdateWorkspace",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"UpdateWorkspace\"",
            "resource_type": "Workspace",
            "floor_path": os.path.join(REFS, "floor_updateworkspace_role_a.cedar"),
        },
        {
            "name": "floor_updateworkspace_role_d",
            "description": "A Role-D user with matching tags must be able to UpdateWorkspace",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"UpdateWorkspace\"",
            "resource_type": "Workspace",
            "floor_path": os.path.join(REFS, "floor_updateworkspace_role_d.cedar"),
        },
        {
            "name": "floor_deleteworkspace_role_a",
            "description": "A Role-A user with matching tags must be able to DeleteWorkspace",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"DeleteWorkspace\"",
            "resource_type": "Workspace",
            "floor_path": os.path.join(REFS, "floor_deleteworkspace_role_a.cedar"),
        },
        {
            "name": "floor_readworkspace_role_a",
            "description": "A Role-A user with matching tags must be able to ReadWorkspace",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ReadWorkspace\"",
            "resource_type": "Workspace",
            "floor_path": os.path.join(REFS, "floor_readworkspace_role_a.cedar"),
        },
        {
            "name": "floor_readworkspace_role_b",
            "description": "A Role-B user with matching tags must be able to ReadWorkspace",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ReadWorkspace\"",
            "resource_type": "Workspace",
            "floor_path": os.path.join(REFS, "floor_readworkspace_role_b.cedar"),
        },
        {
            "name": "floor_readworkspace_role_a_over_role_d_forbid",
            "description": "A user in both Role-A and Role-D with matching Role-A tags must still be able to ReadWorkspace despite the Role-D read forbid",
            "type": "floor",
            "principal_type": "User",
            "action": "Action::\"ReadWorkspace\"",
            "resource_type": "Workspace",
            "floor_path": os.path.join(REFS, "floor_readworkspace_role_a_over_role_d_forbid.cedar"),
        },
        {
            "name": "liveness_updateworkspace",
            "description": "UpdateWorkspace is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"UpdateWorkspace\"",
            "resource_type": "Workspace",
        },
        {
            "name": "liveness_deleteworkspace",
            "description": "DeleteWorkspace is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"DeleteWorkspace\"",
            "resource_type": "Workspace",
        },
        {
            "name": "liveness_readworkspace",
            "description": "ReadWorkspace is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "User",
            "action": "Action::\"ReadWorkspace\"",
            "resource_type": "Workspace",
        },
    ]
