"""Verification plan for streaming_live_event."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "ceiling_freemember_watch_movie",
            "description": "FreeMember may watch a Movie only when it is free",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "ceiling_freemember_watch_movie.cedar"),
        },
        {
            "name": "ceiling_freemember_watch_show",
            "description": "FreeMember may watch a Show only when it is free",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "reference_path": os.path.join(REFS, "ceiling_freemember_watch_show.cedar"),
        },
        {
            "name": "ceiling_subscriber_watch_movie",
            "description": "Subscriber may watch a Movie only when it does not require rent or buy and kid-bedtime forbid does not apply",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "ceiling_subscriber_watch_movie.cedar"),
        },
        {
            "name": "ceiling_subscriber_watch_show",
            "description": "Subscriber may watch a Show only when release timing is allowed and kid-bedtime forbid does not apply",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "reference_path": os.path.join(REFS, "ceiling_subscriber_watch_show.cedar"),
        },
        {
            "name": "ceiling_freemember_rent_movie",
            "description": "FreeMember can never rent a Movie",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"rent\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "ceiling_freemember_rent_movie.cedar"),
        },
        {
            "name": "ceiling_subscriber_rent_movie",
            "description": "Subscriber may rent a Movie only when it is Oscar-nominated and inside the promo window",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"rent\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "ceiling_subscriber_rent_movie.cedar"),
        },
        {
            "name": "ceiling_freemember_buy_movie",
            "description": "FreeMember can never buy a Movie",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"buy\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "ceiling_freemember_buy_movie.cedar"),
        },
        {
            "name": "ceiling_subscriber_buy_movie",
            "description": "Subscriber may buy a Movie only when it is Oscar-nominated and inside the promo window",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"buy\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "ceiling_subscriber_buy_movie.cedar"),
        },
        {
            "name": "ceiling_subscriber_stream_live",
            "description": "Subscriber may stream_live only when the event is live and premium is satisfied when required",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"stream_live\"",
            "resource_type": "LiveEvent",
            "reference_path": os.path.join(REFS, "ceiling_subscriber_stream_live.cedar"),
        },
        {
            "name": "ceiling_subscriber_watch_replay",
            "description": "Subscriber may watch_replay only after the event ends and premium is satisfied when required",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"watch_replay\"",
            "resource_type": "LiveEvent",
            "reference_path": os.path.join(REFS, "ceiling_subscriber_watch_replay.cedar"),
        },
        {
            "name": "floor_freemember_watch_free_movie",
            "description": "FreeMember must be able to watch a free Movie",
            "type": "floor",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "floor_freemember_watch_free_movie.cedar"),
        },
        {
            "name": "floor_freemember_watch_free_show",
            "description": "FreeMember must be able to watch a free Show",
            "type": "floor",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "floor_path": os.path.join(REFS, "floor_freemember_watch_free_show.cedar"),
        },
        {
            "name": "floor_subscriber_watch_movie",
            "description": "A non-kid Subscriber must be able to watch a Movie that does not require rent or buy",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "floor_subscriber_watch_movie.cedar"),
        },
        {
            "name": "floor_subscriber_watch_show_released",
            "description": "A non-kid Subscriber must be able to watch a released Show",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "floor_path": os.path.join(REFS, "floor_subscriber_watch_show_released.cedar"),
        },
        {
            "name": "floor_premium_watch_show_early",
            "description": "A premium non-kid Subscriber must be able to watch an early-access Show within 24 hours of release",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "floor_path": os.path.join(REFS, "floor_premium_watch_show_early.cedar"),
        },
        {
            "name": "floor_subscriber_rent_movie",
            "description": "Subscriber must be able to rent an Oscar-nominated Movie inside the promo window",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"rent\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "floor_subscriber_rent_movie.cedar"),
        },
        {
            "name": "floor_subscriber_buy_movie",
            "description": "Subscriber must be able to buy an Oscar-nominated Movie inside the promo window",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"buy\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "floor_subscriber_buy_movie.cedar"),
        },
        {
            "name": "floor_subscriber_stream_live_basic",
            "description": "A basic Subscriber must be able to stream a live event that does not require premium",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"stream_live\"",
            "resource_type": "LiveEvent",
            "floor_path": os.path.join(REFS, "floor_subscriber_stream_live_basic.cedar"),
        },
        {
            "name": "floor_subscriber_stream_live_premium",
            "description": "A premium Subscriber must be able to stream a live event that requires premium",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"stream_live\"",
            "resource_type": "LiveEvent",
            "floor_path": os.path.join(REFS, "floor_subscriber_stream_live_premium.cedar"),
        },
        {
            "name": "floor_subscriber_watch_replay_basic",
            "description": "A basic Subscriber must be able to watch replay after a non-premium event ends",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"watch_replay\"",
            "resource_type": "LiveEvent",
            "floor_path": os.path.join(REFS, "floor_subscriber_watch_replay_basic.cedar"),
        },
        {
            "name": "floor_subscriber_watch_replay_premium",
            "description": "A premium Subscriber must be able to watch replay after a premium event ends",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"watch_replay\"",
            "resource_type": "LiveEvent",
            "floor_path": os.path.join(REFS, "floor_subscriber_watch_replay_premium.cedar"),
        },
        {
            "name": "liveness_freemember_watch_movie",
            "description": "FreeMember watch Movie is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
        },
        {
            "name": "liveness_freemember_watch_show",
            "description": "FreeMember watch Show is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
        },
        {
            "name": "liveness_subscriber_watch_movie",
            "description": "Subscriber watch Movie is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
        },
        {
            "name": "liveness_subscriber_watch_show",
            "description": "Subscriber watch Show is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
        },
        {
            "name": "liveness_subscriber_rent_movie",
            "description": "Subscriber rent Movie is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"rent\"",
            "resource_type": "Movie",
        },
        {
            "name": "liveness_subscriber_buy_movie",
            "description": "Subscriber buy Movie is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"buy\"",
            "resource_type": "Movie",
        },
        {
            "name": "liveness_subscriber_stream_live",
            "description": "Subscriber stream_live is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"stream_live\"",
            "resource_type": "LiveEvent",
        },
        {
            "name": "liveness_subscriber_watch_replay",
            "description": "Subscriber watch_replay is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"watch_replay\"",
            "resource_type": "LiveEvent",
        },
    ]
