"""Verification plan for streaming_trailer."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "ceiling_freemember_watch_movie",
            "description": "FreeMember may watch a Movie only when it is free",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "ceiling_freemember_watch_movie.cedar"),
        },
        {
            "name": "ceiling_freemember_watch_show",
            "description": "FreeMember may watch a Show only when it is free",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "reference_path": os.path.join(REFS, "ceiling_freemember_watch_show.cedar"),
        },
        {
            "name": "ceiling_subscriber_watch_movie",
            "description": "Subscriber may watch a Movie only when it does not require rent or buy and kid bedtime does not apply",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "ceiling_subscriber_watch_movie.cedar"),
        },
        {
            "name": "ceiling_subscriber_watch_show",
            "description": "Subscriber may watch a Show only when its release timing is allowed and kid bedtime does not apply",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "reference_path": os.path.join(REFS, "ceiling_subscriber_watch_show.cedar"),
        },
        {
            "name": "ceiling_freemember_rent_movie",
            "description": "FreeMember can never rent a Movie",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"rent\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "ceiling_freemember_rent_movie.cedar"),
        },
        {
            "name": "ceiling_subscriber_rent_movie",
            "description": "Subscriber may rent a Movie only when it is Oscar-nominated and inside the promo window",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"rent\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "ceiling_subscriber_rent_movie.cedar"),
        },
        {
            "name": "ceiling_freemember_buy_movie",
            "description": "FreeMember can never buy a Movie",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"buy\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "ceiling_freemember_buy_movie.cedar"),
        },
        {
            "name": "ceiling_subscriber_buy_movie",
            "description": "Subscriber may buy a Movie only when it is Oscar-nominated and inside the promo window",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"buy\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "ceiling_subscriber_buy_movie.cedar"),
        },
        {
            "name": "ceiling_freemember_watch_trailer",
            "description": "FreeMember may watch any Trailer",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"watch_trailer\"",
            "resource_type": "Trailer",
            "reference_path": os.path.join(REFS, "ceiling_freemember_watch_trailer.cedar"),
        },
        {
            "name": "ceiling_subscriber_watch_trailer",
            "description": "Subscriber may watch any Trailer",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"watch_trailer\"",
            "resource_type": "Trailer",
            "reference_path": os.path.join(REFS, "ceiling_subscriber_watch_trailer.cedar"),
        },
        {
            "name": "floor_freemember_watch_free_movie",
            "description": "FreeMember must be able to watch a free Movie",
            "type": "floor",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "floor_freemember_watch_free_movie.cedar"),
        },
        {
            "name": "floor_freemember_watch_free_show",
            "description": "FreeMember must be able to watch a free Show",
            "type": "floor",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "floor_path": os.path.join(REFS, "floor_freemember_watch_free_show.cedar"),
        },
        {
            "name": "floor_subscriber_watch_movie_no_kid",
            "description": "A non-kid Subscriber must be able to watch a Movie that does not require rent or buy",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "floor_subscriber_watch_movie_no_kid.cedar"),
        },
        {
            "name": "floor_subscriber_watch_show_released_no_kid",
            "description": "A non-kid Subscriber must be able to watch a released Show",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "floor_path": os.path.join(REFS, "floor_subscriber_watch_show_released_no_kid.cedar"),
        },
        {
            "name": "floor_premium_watch_show_early_no_kid",
            "description": "A premium non-kid Subscriber must be able to watch an early-access Show within 24 hours of release",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "floor_path": os.path.join(REFS, "floor_premium_watch_show_early_no_kid.cedar"),
        },
        {
            "name": "floor_subscriber_rent_movie",
            "description": "Subscriber must be able to rent an Oscar-nominated Movie inside the promo window",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"rent\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "floor_subscriber_rent_movie.cedar"),
        },
        {
            "name": "floor_subscriber_buy_movie",
            "description": "Subscriber must be able to buy an Oscar-nominated Movie inside the promo window",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"buy\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "floor_subscriber_buy_movie.cedar"),
        },
        {
            "name": "floor_freemember_watch_trailer",
            "description": "FreeMember must be able to watch a Trailer",
            "type": "floor",
            "principal_type": "FreeMember",
            "action": "Action::\"watch_trailer\"",
            "resource_type": "Trailer",
            "floor_path": os.path.join(REFS, "floor_freemember_watch_trailer.cedar"),
        },
        {
            "name": "floor_subscriber_watch_trailer",
            "description": "Subscriber must be able to watch a Trailer",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"watch_trailer\"",
            "resource_type": "Trailer",
            "floor_path": os.path.join(REFS, "floor_subscriber_watch_trailer.cedar"),
        },
        {
            "name": "liveness_freemember_watch_movie",
            "description": "FreeMember watch Movie is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
        },
        {
            "name": "liveness_freemember_watch_show",
            "description": "FreeMember watch Show is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
        },
        {
            "name": "liveness_subscriber_watch_movie",
            "description": "Subscriber watch Movie is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
        },
        {
            "name": "liveness_subscriber_watch_show",
            "description": "Subscriber watch Show is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
        },
        {
            "name": "liveness_subscriber_rent_movie",
            "description": "Subscriber rent Movie is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"rent\"",
            "resource_type": "Movie",
        },
        {
            "name": "liveness_subscriber_buy_movie",
            "description": "Subscriber buy Movie is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"buy\"",
            "resource_type": "Movie",
        },
        {
            "name": "liveness_freemember_watch_trailer",
            "description": "FreeMember watch_trailer is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "FreeMember",
            "action": "Action::\"watch_trailer\"",
            "resource_type": "Trailer",
        },
        {
            "name": "liveness_subscriber_watch_trailer",
            "description": "Subscriber watch_trailer is not trivially deny-all",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"watch_trailer\"",
            "resource_type": "Trailer",
        },
    ]
