"""Verification plan for streaming_geo_blocklist."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "freemember_movie_only_free_not_geo_blocked",
            "description": "FreeMember may watch a Movie only when the movie is free and the user's region is not blocklisted",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "freemember_movie_only_free_not_geo_blocked.cedar"),
        },
        {
            "name": "freemember_show_only_free",
            "description": "FreeMember may watch a Show only when the show is free",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "reference_path": os.path.join(REFS, "freemember_show_only_free.cedar"),
        },
        {
            "name": "subscriber_movie_no_rent_buy_not_geo_blocked",
            "description": "Subscriber may watch a Movie only when it does not require rent-or-buy and the user's region is not blocklisted",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "subscriber_movie_no_rent_buy_not_geo_blocked.cedar"),
        },
        {
            "name": "subscriber_show_premium_or_not_early",
            "description": "Subscriber may watch a Show only when !isEarlyAccess or tier==premium",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "reference_path": os.path.join(REFS, "subscriber_show_premium_or_not_early.cedar"),
        },
        {
            "name": "kid_bedtime_no_watch_movie",
            "description": "Subscriber may watch a Movie only when NOT (isKid AND localTime in bedtime)",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "kid_bedtime_no_watch_movie.cedar"),
        },
        {
            "name": "kid_bedtime_no_watch_show",
            "description": "Subscriber may watch a Show only when NOT (isKid AND localTime in bedtime)",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "reference_path": os.path.join(REFS, "kid_bedtime_no_watch_show.cedar"),
        },
        {
            "name": "freemember_must_watch_free_movie_not_geo_blocked",
            "description": "FreeMember MUST be permitted to watch any free Movie that is not geo-blocked in the user's region",
            "type": "floor",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "freemember_must_watch_free_movie_not_geo_blocked.cedar"),
        },
        {
            "name": "freemember_must_watch_free_show",
            "description": "FreeMember MUST be permitted to watch any free Show",
            "type": "floor",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "floor_path": os.path.join(REFS, "freemember_must_watch_free_show.cedar"),
        },
        {
            "name": "subscriber_must_watch_movie_no_rent_no_kid_no_geo",
            "description": "Subscriber (non-kid) MUST be permitted to watch any non-rent-or-buy Movie that is not geo-blocked",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "subscriber_must_watch_movie_no_rent_no_kid_no_geo.cedar"),
        },
        {
            "name": "subscriber_must_watch_show_not_early_no_kid",
            "description": "Subscriber (non-kid) MUST be permitted to watch any !isEarlyAccess Show",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "floor_path": os.path.join(REFS, "subscriber_must_watch_show_not_early_no_kid.cedar"),
        },
        {
            "name": "premium_must_watch_show_early_no_kid",
            "description": "Premium Subscriber (non-kid) MUST be permitted to watch any isEarlyAccess Show",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "floor_path": os.path.join(REFS, "premium_must_watch_show_early_no_kid.cedar"),
        },
        {
            "name": "freemember_no_rent",
            "description": "FreeMember can never rent a Movie",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"rent\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "freemember_no_rent.cedar"),
        },
        {
            "name": "subscriber_rent_only_oscar_in_window",
            "description": "Subscriber may rent a Movie only when isOscarNominated and now is in the promo window",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"rent\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "subscriber_rent_only_oscar_in_window.cedar"),
        },
        {
            "name": "subscriber_must_rent_oscar_in_window",
            "description": "Subscriber MUST be permitted to rent any isOscarNominated Movie in window",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"rent\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "subscriber_must_rent_oscar_in_window.cedar"),
        },
        {
            "name": "freemember_no_buy",
            "description": "FreeMember can never buy a Movie",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"buy\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "freemember_no_buy.cedar"),
        },
        {
            "name": "subscriber_buy_only_oscar_in_window",
            "description": "Subscriber may buy a Movie only when isOscarNominated and now is in the promo window",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"buy\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "subscriber_buy_only_oscar_in_window.cedar"),
        },
        {
            "name": "subscriber_must_buy_oscar_in_window",
            "description": "Subscriber MUST be permitted to buy any isOscarNominated Movie in window",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"buy\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "subscriber_must_buy_oscar_in_window.cedar"),
        },
        {
            "name": "liveness_freemember_watch_movie",
            "description": "FreeMember + watch + Movie has at least one permitted request",
            "type": "always-denies-liveness",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
        },
        {
            "name": "liveness_freemember_watch_show",
            "description": "FreeMember + watch + Show has at least one permitted request",
            "type": "always-denies-liveness",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
        },
        {
            "name": "liveness_subscriber_watch_movie",
            "description": "Subscriber + watch + Movie has at least one permitted request",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
        },
        {
            "name": "liveness_subscriber_watch_show",
            "description": "Subscriber + watch + Show has at least one permitted request",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
        },
        {
            "name": "liveness_subscriber_rent_movie",
            "description": "Subscriber + rent + Movie has at least one permitted request",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"rent\"",
            "resource_type": "Movie",
        },
        {
            "name": "liveness_subscriber_buy_movie",
            "description": "Subscriber + buy + Movie has at least one permitted request",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"buy\"",
            "resource_type": "Movie",
        },
    ]
