"""Verification plan for streaming_podcast."""
import os

REFS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "references")


def get_checks():
    return [
        {
            "name": "freemember_movie_only_free",
            "description": "FreeMember may watch a Movie only when the movie is free",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "freemember_movie_only_free.cedar"),
        },
        {
            "name": "freemember_show_only_free",
            "description": "FreeMember may watch a Show only when the show is free",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "reference_path": os.path.join(REFS, "freemember_show_only_free.cedar"),
        },
        {
            "name": "subscriber_movie_no_rent_buy",
            "description": "Subscriber may watch a Movie only when !needsRentOrBuy",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "subscriber_movie_no_rent_buy.cedar"),
        },
        {
            "name": "subscriber_show_premium_or_not_early",
            "description": "Subscriber may watch a Show only when !isEarlyAccess OR tier==premium",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "reference_path": os.path.join(REFS, "subscriber_show_premium_or_not_early.cedar"),
        },
        {
            "name": "kid_bedtime_no_watch_movie",
            "description": "Subscriber may watch a Movie only when NOT (isKid AND localTime in bedtime)",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "kid_bedtime_no_watch_movie.cedar"),
        },
        {
            "name": "kid_bedtime_no_watch_show",
            "description": "Subscriber may watch a Show only when NOT (isKid AND localTime in bedtime)",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "reference_path": os.path.join(REFS, "kid_bedtime_no_watch_show.cedar"),
        },
        {
            "name": "freemember_listen_podcast_only_free_nonexclusive",
            "description": "FreeMember may listen to a Podcast only when it is free and not exclusive",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"listen_podcast\"",
            "resource_type": "Podcast",
            "reference_path": os.path.join(REFS, "freemember_listen_podcast_only_free_nonexclusive.cedar"),
        },
        {
            "name": "subscriber_listen_podcast_any_or_premium_exclusive",
            "description": "Subscriber may listen to a Podcast only when it is not exclusive or the subscriber is premium",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"listen_podcast\"",
            "resource_type": "Podcast",
            "reference_path": os.path.join(REFS, "subscriber_listen_podcast_any_or_premium_exclusive.cedar"),
        },
        {
            "name": "subscriber_download_podcast_any",
            "description": "Subscriber may download any Podcast",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"download_podcast\"",
            "resource_type": "Podcast",
            "reference_path": os.path.join(REFS, "subscriber_download_podcast_any.cedar"),
        },
        {
            "name": "freemember_must_watch_free_movie",
            "description": "FreeMember MUST be permitted to watch any free Movie",
            "type": "floor",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "freemember_must_watch_free_movie.cedar"),
        },
        {
            "name": "freemember_must_watch_free_show",
            "description": "FreeMember MUST be permitted to watch any free Show",
            "type": "floor",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "floor_path": os.path.join(REFS, "freemember_must_watch_free_show.cedar"),
        },
        {
            "name": "subscriber_must_watch_movie_no_rent_no_kid",
            "description": "Subscriber (non-kid) MUST be permitted to watch any !needsRentOrBuy Movie",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "subscriber_must_watch_movie_no_rent_no_kid.cedar"),
        },
        {
            "name": "subscriber_must_watch_show_not_early_no_kid",
            "description": "Subscriber (non-kid) MUST be permitted to watch any !isEarlyAccess Show",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "floor_path": os.path.join(REFS, "subscriber_must_watch_show_not_early_no_kid.cedar"),
        },
        {
            "name": "premium_must_watch_show_early_no_kid",
            "description": "Premium Subscriber (non-kid) MUST be permitted to watch any isEarlyAccess Show",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
            "floor_path": os.path.join(REFS, "premium_must_watch_show_early_no_kid.cedar"),
        },
        {
            "name": "freemember_must_listen_free_nonexclusive_podcast",
            "description": "FreeMember MUST be permitted to listen to any free, non-exclusive Podcast",
            "type": "floor",
            "principal_type": "FreeMember",
            "action": "Action::\"listen_podcast\"",
            "resource_type": "Podcast",
            "floor_path": os.path.join(REFS, "freemember_must_listen_free_nonexclusive_podcast.cedar"),
        },
        {
            "name": "subscriber_must_listen_nonexclusive_podcast",
            "description": "Subscriber MUST be permitted to listen to any non-exclusive Podcast",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"listen_podcast\"",
            "resource_type": "Podcast",
            "floor_path": os.path.join(REFS, "subscriber_must_listen_nonexclusive_podcast.cedar"),
        },
        {
            "name": "premium_must_listen_exclusive_podcast",
            "description": "Premium Subscriber MUST be permitted to listen to any exclusive Podcast",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"listen_podcast\"",
            "resource_type": "Podcast",
            "floor_path": os.path.join(REFS, "premium_must_listen_exclusive_podcast.cedar"),
        },
        {
            "name": "subscriber_must_download_podcast",
            "description": "Subscriber MUST be permitted to download any Podcast",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"download_podcast\"",
            "resource_type": "Podcast",
            "floor_path": os.path.join(REFS, "subscriber_must_download_podcast.cedar"),
        },
        {
            "name": "freemember_no_rent",
            "description": "FreeMember can NEVER rent a Movie",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"rent\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "freemember_no_rent.cedar"),
        },
        {
            "name": "subscriber_rent_only_oscar_in_window",
            "description": "Subscriber may rent a Movie only when isOscarNominated AND now in Oscars window",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"rent\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "subscriber_rent_only_oscar_in_window.cedar"),
        },
        {
            "name": "subscriber_must_rent_oscar_in_window",
            "description": "Subscriber MUST be permitted to rent any isOscarNominated Movie in window",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"rent\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "subscriber_must_rent_oscar_in_window.cedar"),
        },
        {
            "name": "freemember_no_buy",
            "description": "FreeMember can NEVER buy a Movie",
            "type": "implies",
            "principal_type": "FreeMember",
            "action": "Action::\"buy\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "freemember_no_buy.cedar"),
        },
        {
            "name": "subscriber_buy_only_oscar_in_window",
            "description": "Subscriber may buy a Movie only when isOscarNominated AND now in Oscars window",
            "type": "implies",
            "principal_type": "Subscriber",
            "action": "Action::\"buy\"",
            "resource_type": "Movie",
            "reference_path": os.path.join(REFS, "subscriber_buy_only_oscar_in_window.cedar"),
        },
        {
            "name": "subscriber_must_buy_oscar_in_window",
            "description": "Subscriber MUST be permitted to buy any isOscarNominated Movie in window",
            "type": "floor",
            "principal_type": "Subscriber",
            "action": "Action::\"buy\"",
            "resource_type": "Movie",
            "floor_path": os.path.join(REFS, "subscriber_must_buy_oscar_in_window.cedar"),
        },
        {
            "name": "liveness_freemember_watch_movie",
            "description": "FreeMember + watch + Movie has at least one permitted request",
            "type": "always-denies-liveness",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
        },
        {
            "name": "liveness_freemember_watch_show",
            "description": "FreeMember + watch + Show has at least one permitted request",
            "type": "always-denies-liveness",
            "principal_type": "FreeMember",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
        },
        {
            "name": "liveness_subscriber_watch_movie",
            "description": "Subscriber + watch + Movie has at least one permitted request",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Movie",
        },
        {
            "name": "liveness_subscriber_watch_show",
            "description": "Subscriber + watch + Show has at least one permitted request",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"watch\"",
            "resource_type": "Show",
        },
        {
            "name": "liveness_freemember_listen_podcast",
            "description": "FreeMember + listen_podcast + Podcast has at least one permitted request",
            "type": "always-denies-liveness",
            "principal_type": "FreeMember",
            "action": "Action::\"listen_podcast\"",
            "resource_type": "Podcast",
        },
        {
            "name": "liveness_subscriber_listen_podcast",
            "description": "Subscriber + listen_podcast + Podcast has at least one permitted request",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"listen_podcast\"",
            "resource_type": "Podcast",
        },
        {
            "name": "liveness_subscriber_download_podcast",
            "description": "Subscriber + download_podcast + Podcast has at least one permitted request",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"download_podcast\"",
            "resource_type": "Podcast",
        },
        {
            "name": "liveness_subscriber_rent_movie",
            "description": "Subscriber + rent + Movie has at least one permitted request",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"rent\"",
            "resource_type": "Movie",
        },
        {
            "name": "liveness_subscriber_buy_movie",
            "description": "Subscriber + buy + Movie has at least one permitted request",
            "type": "always-denies-liveness",
            "principal_type": "Subscriber",
            "action": "Action::\"buy\"",
            "resource_type": "Movie",
        },
    ]
